import './globals.css'
import { Providers } from "./providers";
import { Urbanist } from 'next/font/google';

import { Link } from '@nextui-org/link';
import { Navbar, NavbarBrand, NavbarContent, NavbarItem } from '@nextui-org/navbar';

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Providers>

          <Navbar>
            <NavbarBrand>
              <p className="font-bold text-inherit">ACME</p>
            </NavbarBrand>

            <NavbarContent className="hidden sm:flex gap-4" justify="center">
              <NavbarItem>
                <Link color="foreground" href="/person/">
                  Miembros
                </Link>
              </NavbarItem>
              <NavbarItem isActive>
                <Link href="/group/" aria-current="page">
                  Grupos
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="#">
                  Labs
                </Link>
              </NavbarItem>
            </NavbarContent>

            {/* <NavbarContent justify="end">
              <NavbarItem className="hidden lg:flex">
                <Link href="#">Login</Link>
              </NavbarItem>
              <NavbarItem>
                <Button as={Link} color="primary" href="#" variant="flat">
                  Sign Up
                </Button>
              </NavbarItem>
            </NavbarContent> */}
          </Navbar>

        
          {children}
        </Providers>
      </body>
    </html>
  )
}
